apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-dashboard
  labels:
    name: kubernetes-dashboard
---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  labels:
    name: tailscale
